Replaced getElementById with querySelector
AxcelEspinal-Ksquare/project2_conway pull request #10
Opened 2022-10-06 21:00 UTC by AxcelEspinal-Ksquare

I added the 'c' in the id because the querySelector method uses CSS3 selectors for querying the DOM and CSS3 doesn't support ID selectors that start with a digit. Then, I replaced the 'c' when separating the id to get the row and column.

2022-10-06 21:23 UTC, GabrielOsorno-Ksquare requested changes
cell declarations could use const keyword.

2022-10-07 03:33 UTC, AxcelEspinal-Ksquare commented
Changed what you said. Please check.

2022-10-07 03:49 UTC, GabrielOsorno-Ksquare commented
Changed some other let for const

2022-10-07 03:51 UTC, GabrielOsorno-Ksquare approved these changes

2022-10-07 03:51 UTC, merged